---
- name: install essential dev tools
  apt:
    state: present
    pkg:
      - emacs
      - gnupg2
      - openssh-server
      - openvpn
      - zsh
  become: True
  tags: [emacs, essentials]

- name: install convenient shell tools
  become: True
  tags: [convenience]
  apt:
    state: present
    pkg:
      - aspell-en # writing
      - build-essential
      - cloc
      - curl
      - exiftool
      - imagemagick
      - jq
      - parallel
      - pv
      - silversearcher-ag
      - slurm
      - stow
      - tmux
      - tree
      - wamerican # /usr/share/dict/words
      - whois
      - wordnet # writing
      - xsel

- name: create the src working directory
  file: path=~/src/vendor state=directory
  tags: [essentials]

- name: create XDG_CONFIG_HOME
  file: path=~/.config state=directory
  tags: [essentials]

- name: switch to ZSH
  user: name={{ansible_user}} shell=/usr/bin/zsh
  become: true
  tags: [essentials]

- name: clone .emacs.d
  git: repo=git@github.com:jmdeldin/.emacs.d.git dest=~/.emacs.d update=False
  tags: [essentials]

- name: disable password ssh
  lineinfile: dest=/etc/ssh/sshd_config state=present
              line="PasswordAuthentication no"
  tags: [net]
  become: True

- name: increase limits for neo4j
  copy: src=../templates/etc/security/limits.conf dest=/etc/security/limits.conf
  tags: [neo4j]
  become: True

- name: enable limits
  lineinfile: dest=/etc/pam.d/su state=present
              line="session required pam_limits.so"
  tags: [neo4j]
  become: True

- name: install vagrant dependencies
  become: True
  tags: vagrant
  apt:
    state: present
    pkg:
      - nfs-kernel-server
      - virtualbox

- name: download vagrant
  tags: vagrant
  get_url:
    dest: ~/src/vendor/vagrant_2.2.18.deb
    url: https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_x86_64.deb

- name: install vagrant
  become: True
  apt: deb=/home/{{ansible_ssh_user}}/src/vendor/vagrant_2.2.18.deb

- name: make NFS password-free
  become: True
  tags: vagrant
  copy:
    src: ../templates/etc/sudoers.d/vagrant
    dest: /etc/sudoers.d/vagrant
