---
- name: install essential dev tools
  apt: pkg={{item}} state=installed
  become: True
  tags: [emacs, essentials]
  with_items:
    - emacs
    - gnupg2
    - openssh-server
    - openvpn
    - zsh

- name: install convenient shell tools
  apt: pkg={{item}} state=installed
  become: True
  tags: [convenience]
  with_items:
    - aspell-en # writing
    - build-essential
    - cloc
    - curl
    - exiftool
    - imagemagick
    - parallel
    - pv
    - silversearcher-ag
    - slurm
    - stow
    - tmux
    - tree
    - wamerican # /usr/share/dict/words
    - whois
    - wordnet # writing
    - xsel

- name: create the src working directory
  file: path=~/src/vendor state=directory
  tags: [essentials]

- name: create XDG_CONFIG_HOME
  file: path=~/.config state=directory
  tags: [essentials]

- name: switch to ZSH
  user: name={{ansible_user}} shell=/usr/bin/zsh
  become: true
  tags: [essentials]

- name: clone .emacs.d
  git: repo=git@github.com:jmdeldin/.emacs.d.git dest=~/.emacs.d update=False
  tags: [essentials]

- name: disable password ssh
  lineinfile: dest=/etc/ssh/sshd_config state=present
              line="PasswordAuthentication no"
  tags: [net]
  become: True

- name: increase limits for neo4j
  copy: src=../templates/etc/security/limits.conf dest=/etc/security/limits.conf
  tags: [neo4j]
  become: True

- name: enable limits
  lineinfile: dest=/etc/pam.d/su state=present
              line="session required pam_limits.so"
  tags: [neo4j]
  become: True

- name: install vagrant dependencies
  apt: pkg={{item}} state=installed
  become: True
  tags: [vagrant]
  with_items:
    - nfs-kernel-server
    - virtualbox

- name: download vagrant
  tags: vm
  get_url:
    dest: ~/src/vendor/vagrant_2.0.1.deb
    url: https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb

- name: install vagrant
  become: True
  apt: deb=/home/{{ansible_ssh_user}}/src/vendor/vagrant_2.0.1.deb
