# Setup for my Thinkpad T460p.
#
# Ensure you do this for VirtualBox: BIOS -> Security > Virtualization >
# Enable Intel stuff.
---
- hosts: 127.0.0.1
  vars:
    default_ruby: 2.4.2
    sudo_user: "{{ansible_ssh_user}}"
    sudo_filename: ansible_added
    sudo_commands:
      - "/home/{{ansible_ssh_user}}/bin/iggy"
  roles:
    - base
    - devel
    - firewall
    - golang
    - janitor
    - ruby
    - sudoers
  tasks:

    - name: window manager needs
      become: True
      apt: pkg={{item}} state=installed
      tags: wm
      with_items:
        - acpi
        - arandr # easier than memorizing xrandr for mirroring
        - compton
        - i3-wm
        - i3lock
        - i3status
        - rofi
        - rxvt-unicode
        - scrot
        - wicd
        - xinit
        - xinput

    # https://bugs.launchpad.net/ubuntu/+source/isc-dhcp/+bug/1704174
    - name: fix ubuntu wicd-apparmor bug
      become: True
      tags: net
      lineinfile:
        path: /etc/apparmor.d/sbin.dhclient
        insertafter: '/usr/share/synce-hal/dhclient.conf r,'
        line: '/var/lib/wicd/dhclient.conf r,'
        state: present

    - name: add repo for latest 0ad
      become: True
      apt_repository: repo=ppa:wfg/0ad
      tags: games

    - name: install 0ad
      become: True
      apt: pkg=0ad state=installed
      tags: games

    - name: install borg
      become: True
      tags: backup
      apt: pkg=borgbackup state=installed

    - name: install browsers
      become: True
      tags: browsers
      apt: pkg={{item}} state=installed
      with_items:
        - chromium-browser
        - firefox
        - fonts-ubuntu-font-family-console
        - ttf-ubuntu-font-family

    - name: install GUI tools
      become: True
      tags: gui
      apt: pkg={{item}} state=installed
      with_items:
        - guvcview # webcam
        - pinentry-gtk2
        - redshift

    - name: install creative tools
      become: True
      tags: creative
      apt: pkg={{item}} state=installed
      with_items:
        - darktable
        - feh
        - gimp
        - git-annex
        - graphviz
        - libreoffice
        - xournal # pdf annotations
        - zathura # pdf viewer

    - name: install media tools
      become: True
      tags: media
      apt: pkg={{item}} state=installed
      with_items:
        - mpv

    - name: install terminal tools
      become: True
      tags: term
      apt: pkg={{item}} state=installed
      with_items:
        - firejail
        - iotop
        - gnuplot
        - ledger
        - unzip
        - wakeonlan
        - zip

    - name: install music packages
      become: True
      tags: music
      apt: pkg={{item}} state=installed
      with_items:
        - alsa-utils
        - exfalso # tag management
        - libavcodec-extra # for mp3s
        - mpc
        - mpd
        - ncmpc
        - pavucontrol

    - name: disable system-wide mpd
      become: True
      service: enabled=no name=mpd
      tags: music

    - name: Mount /tmp as tmpfs
      become: True
      tags: space
      mount:
        name: /tmp
        src: tmpfs
        fstype: tmpfs
        opts: "size=2048M"
        state: mounted

    - name: setup bluetooth
      become: True
      tags: bluetooth
      apt: pkg={{item}} state=installed
      with_items:
        - bluez
        - pulseaudio-module-bluetooth

    - name: Mount tiny hard drive
      become: True
      tags: space
      mount:
        name: /media/jmdeldin/scratch
        src: /dev/sdb1
        fstype: ext4
        state: present

    - name: Destroy Ubuntu motd spyware service
      become: True
      tags: cleanup
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - /etc/default/motd-news
        - /etc/update-motd.d

    - name: Remove terrible network service -- this hangs reboots by 2 min
      become: True
      systemd:
        name: systemd-networkd-wait-online.service
        enabled: no
        state: stopped
        daemon_reload: yes

    - name: Install email tools
      become: True
      tags: email
      apt: pkg={{item}} state=installed
      with_items:
        - mu4e
        - offlineimap

    - name: make firejail 0.9.5 work for network connections (remove line)
      become: True
      tags: security
      lineinfile:
        path: /etc/firejail/disable-common.inc
        regexp: '^blacklist /var/run/systemd$'
        state: absent

    - name: make firejail 0.9.5 work for network connections (replace + comment out)
      become: True
      tags: security
      lineinfile:
        path: /etc/firejail/disable-common.inc
        line: '# blacklist /var/run/systemd'
        state: present

    - name: setup printer
      become: True
      tags: printer
      apt: pkg={{item}} state=installed
      with_items:
        - cups
        - lpr
