# Setup for my Thinkpad T460p.
#
# Ensure you do this for VirtualBox: BIOS -> Security > Virtualization >
# Enable Intel stuff.
---
- hosts: localhost
  roles:
    - base
    - janitor
    - devel
    - firewall

  tasks:
    - name: add repo for latest 0ad
      apt_repository: repo=ppa:wfg/0ad
      become: True
      tags: [games]

    - name: install misc software
      apt: pkg={{item}} state=installed
      become: True
      tags: [system76, packages]
      with_items:
        - 0ad
        - borgbackup
        - chromium-browser
        - darktable
        - gcolor2 # color picker
        - gimp
        - gnome-tweak-tool # TODO REMOVE
        - guvcview # webcam
        - gparted
        - ledger
        - mplayer
        - redshift
        - unity-tweak-tool # TODO REMOVE
        - xournal

    - name: kill stupid update notifier
      file: path={{item}} state=absent
      become: True
      tags: [system76]
      with_items:
        - /etc/cron.weekly/update-notifier-common
        - /etc/cron.daily/update-notifier-common

    - name: install i3 stuff
      apt: pkg={{item}} state=installed
      become: True
      with_items:
        - compton
        - i3
        - pavucontrol
        - rxvt-unicode
        - xbacklight
