---
- hosts: all
  vars:
    default_ruby: 1.9.3-p547
    bundler_version: 1.8.0
  roles:
    - base
    - elasticsearch
    - highseas
    - nginx_proxy
    - ruby
    - vagrant
  tasks:
    - name: install sphinx and MQTT
      become: True
      apt: pkg={{item}} state=installed
      with_items:
        - mosquitto
        - mosquitto-clients
        - sphinxsearch

    - name: open up mysql
      become: True
      lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address\s*=(.+)$'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: configure binlog
      become: True
      lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
