---
- hosts: all
  vars:
    default_ruby: jruby-1.7.26
    bundler_version: 1.8
  roles:
    - base
    - highseas
    - node
    - nginx_proxy
    - ruby
    - vagrant
  tasks:
    - name: install node deps
      become: True
      npm:
        global: yes
        name:
          - gulp
          - bower
          # TODO: May need these:
          # - yo
          # - node-gyp
          # - karma
          # - protractor
          # - phantomjs
