---
- hosts: all
  vars:
    default_ruby: jruby-9.1.12.0
    bundler_version: 1.16.1
    default_node: v10.1.0
  roles:
    - base
    - highseas
    - nginx_proxy
    - ruby
    - vagrant
  tasks:
    - name: install default node
      shell: "bash -c 'source ~/.nvm/nvm.sh && nvm install {{default_node}} && nvm alias default {{default_node}}'"
      args:
        creates: ~/.nvm/versions/node/{{default_node}}
      tags: [node]
