---
- hosts: all
  vars:
    default_ruby: jruby-1.7.26
    old_ruby: True
    bundler_version: 1.7.8
    binlog: True
  roles:
    - base
    - highseas
    - nginx_proxy
    - ruby
    - vagrant
  tasks:
    - name: install sphinx and MQTT
      become: True
      apt:
        state: present
        pkg:
          - mosquitto
          - mosquitto-clients
          - sphinxsearch

    - name: open up mysql
      become: True
      lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address\s*=(.+)$'
        line: 'bind-address = 0.0.0.0'
        state: present
      notify: restart mysql

    - name: configure binlog
      become: True
      lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^#log_bin(.*)$'
        state: absent

    - name: configure binlog
      become: True
      lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        line: 'log_bin = /var/log/mysql/mysql-bin.log'
        state: present

    - name: open redis up
      become: True
      lineinfile:
        dest: /etc/redis/redis.conf
        regexp: '^bind (.+)$'
        line: 'bind 0.0.0.0'
        state: present
    # NEED TO restart redis afterwards

    - name: open memcached up
      become: True
      lineinfile:
        dest: /etc/memcached.conf
        regexp: '^-l 127.0.0.1'
        line: '-l 0.0.0.0'
        state: present

    - name: install mysql workbench
      become: True
      apt: pkg=mysql-workbench state=present
