---
- hosts: all
  vars:
    default_ruby: 1.9.3-p551
    old_ruby: True
    bundler_version: 1.8.0
    elasticsearch_version: 1.7.4
  roles:
    - base
    - elasticsearch
    - highseas
    - nginx_proxy
    - ruby
    - vagrant
  tasks:
    - name: install sphinx and MQTT
      become: True
      apt: pkg={{item}} state=present
      with_items:
        - mosquitto
        - mosquitto-clients
        - sphinxsearch

    - name: open up mysql
      become: True
      lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address\s*=(.+)$'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: configure binlog
      become: True
      lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^#log_bin(.*)$'
        state: absent

    - name: configure binlog
      become: True
      lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        line: 'log_bin = /var/log/mysql/mysql-bin.log'
        state: present

    - name: open redis up
      become: True
      lineinfile:
        dest: /etc/redis/redis.conf
        regexp: '^bind (.+)$'
        line: 'bind 0.0.0.0'
        state: present

    - name: install mysql workbench
      become: True
      apt: pkg=mysql-workbench state=present

  handlers:
    - name: restart redis
      become: True
      service: name=redis state=restarted
