---
- hosts: all
  vars:
    default_ruby: jruby-1.7.26
    bundler_version: 1.14.6
    zeromq_version: 3.2.4
    elasticsearch_version: 1.7.3
  roles:
    - base
    - elasticsearch
    - highseas
    - nginx_proxy
    - ruby
    - vagrant
  tasks:
    - name: prereqs for 0mq
      become: True
      apt: pkg={{item}} state=present
      with_items:
        - automake
        - build-essential
        - libtool-bin

    - name: create a directory for stashing downloads
      become: True
      file:
        path: /opt/src
        state: directory

    - name: download 0mq
      become: True
      unarchive:
        src: http://download.zeromq.org/zeromq-{{zeromq_version}}.tar.gz
        remote_src: yes
        dest: /opt/src
        creates: /opt/src/zeromq-{{zeromq_version}}

    - name: install 0mq
      become: True
      shell: './autogen.sh && ./configure --prefix=/usr/local --datarootdir=/usr/local/share && make && make install'
      args:
        chdir: /opt/src/zeromq-{{zeromq_version}}
        creates: /usr/local/lib/libzmq.so
