---
- hosts: all
  vars:
    default_ruby: jruby-1.7.26
    bundler_version: 1.7.8
  roles:
    - base
    - highseas
    - nginx_proxy
    - ruby
    - vagrant
  tasks:
    - apt:
        pkg: imagemagick
        state: present
