---
- hosts: all
  vars:
    default_ruby: 1.9.3-p547
    bundler_version: 1.8.0
  roles:
    - base
    - elasticsearch
    - highseas
    - nginx_proxy
    - ruby
    - vagrant
  tasks:
    - name: install sphinx
      become: True
      apt: pkg=sphinxsearch state=installed
