---
- hosts: all
  vars:
    default_ruby: jruby-1.7.19
  roles:
    - base
    - highseas
    - ruby
    - vagrant
  tasks:
    - name: Install misc. programs
      apt: pkg={{item}} state=installed
      become: True
      with_items:
        - mariadb-server
        - memcached
        - redis-server
