---
- hosts: vcr
  roles:
    - base
    - backup_server
    - firewall
    - force_ipv4
    - seedbox
  vars:
    seedbox_user: netbook

  tasks:
    - name: Install VCR packages
      become: True
      apt:
        state: present
        pkg:
          - firmware-realtek
          - libav-tools
          - tmux

    - name: add non-free repo for firmware
      become: True
      lineinfile:
        dest: /etc/apt/sources.list
        state: present
        line: "deb http://mirrors.cat.pdx.edu/debian/ stretch non-free"
