---
- hosts: vcr
  roles:
    - base
    - backup_server
    - seedbox
  vars:
    seedbox_user: netbook

  tasks:
    - name: Install VCR packages
      become: True
      apt: pkg={{item}} state=installed
      with_items:
        - libav-tools
        - tmux
