---
- hosts: vcr
  roles:
    - base
    - seedbox
  vars:
    seedbox_user: netbook

  tasks:
    - name: Install VCR packages
      become: True
      apt: pkg={{item}} state=installed
      with_items:
        - borgbackup
        - ffmpeg
        - lvm2
        - tmux

    - name: create chromebook user
      become: True
      user:
        name: netbook
        password: "{{ 'vcr' | password_hash('sha512') }}"
        shell: /bin/dash

    - name: clean netbook directory
      become: True
      file: path=/home/netbook/{{item}} state=absent
      with_items:
        - examples.desktop
        - .bashrc
        - .bash_logout
        - .profile
