---
- name: install basic packages
  become: True
  apt: state=present name={{item}}
  with_items:
    - zip

- name: copy SSH keys over
  copy:
    src: ~/{{item}}
    dest: /home/{{ansible_ssh_user}}/{{item}}
    mode: 0600
  with_items:
    - .ssh/id_rsa
    - .ssh/id_rsa.pub

- name: automatically add keys to SSH agent when needed
  lineinfile:
    dest: ~/.ssh/config
    line: "AddKeysToAgent yes"
    state: present
    create: True
    mode: 0600

- name: source custom app config
  lineinfile:
    dest: ~/.bashrc
    state: present
    line: "[ -f /vagrant/app_env.sh ] && source /vagrant/app_env.sh"
