# Tasks for an Ubuntu development machine at The Clymb
- name: "add Percona's key"
  apt_key: keyserver=keys.gnupg.net id=1C4CBDCDCD2EFD2A
  become: True
  tags: [mysql, theclymb]

- name: add repo for Percona
  apt_repository: repo='{{item}} http://repo.percona.com/apt {{ubuntu}} main'
  become: True
  tags: [mysql, theclymb]
  with_items:
    - deb
    - deb-src

- name: install mysql
  apt: pkg={{item}} state=present
  become: True
  tags: [mysql, packages, theclymb]
  with_items:
    - percona-server-server-5.6
    - libmysqlclient-dev

- name: copy my.cnf
  copy: src=templates/etc/mysql/my.cnf dest=/etc/mysql/my.cnf
  become: True
  tags: [mysql, theclymb]
  notify: [restart MySQL]

- name: download elasticsearch
  get_url: dest=~/src/vendor/es.deb url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.1.deb
  tags: [search, theclymb]

- name: install elasticsearch
  command: dpkg -i /home/{{ansible_ssh_user}}/src/vendor/es.deb creates=/etc/init.d/elasticsearch
  become: True
  tags: [search, theclymb]
  notify: [start ES]

- name: install ruby gem lib dependencies
  apt: pkg={{item}} state=present
  tags: [packages, ruby, theclymb]
  become: True
  with_items:
    - libqt5webkit5-dev # capybara
    - libsqlite3-dev    # mailcatcher gem
    - libxslt1-dev      # ruby-xslt
    - memcached         # dalli
    - nodejs
    - npm
    - pngquant
    - qt5-default       # capybara
    - redis-server      # redis
    - xvfb              # capybara

- name: install base gems
  gem: name={{item}} state=present include_dependencies=True
  notify: [rehash ruby gems]
  tags: [ruby, theclymb]
  with_items:
    - db-rotator
    - mailcatcher
    - zeus

- name: install other utilities
  apt: pkg={{item}} state=present
  become: True
  tags: [packages, theclymb]
  with_items:
    - unrar # modern.ie VMs
    - virtualbox
    - wkhtmltopdf

- name: symlink wkhtmltopdf to somewhere the ruby gem knows
  file: path=/usr/local/bin/wkhtmltopdf src=/usr/bin/wkhtmltopdf state=link
  become: True
