- name: install system deps
  become: True
  apt:
    state: present
    pkg:
      - libmysqlclient-dev
      - libxml2-dev # nokogiri
      - libxslt-dev # nokogiri
      - mariadb-server
      - memcached
      - openjdk-8-jre-headless
      - redis-server

- name: Install nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm
    update: False
    accept_hostkey: True

- name: Copy binlog template over
  copy:
    src: ../templates/etc/mysql/conf.d/binlog.conf
    dest: /etc/mysql/conf.d/binlog.conf
  become: True
  when: binlog is defined
  notify: restart mysql

- name: Copy mysql config template over
  copy:
    src: ../templates/etc/mysql/conf.d/bigger_keys.cnf
    dest: /etc/mysql/conf.d/bigger_keys.cnf
  become: True
  when: binlog is defined
  notify: restart mysql
