- name: install system deps
  apt: pkg={{item}} state=present
  become: True
  with_items:
    - libcurl4-openssl-dev
    - libmysqlclient-dev
    - libxml2-dev # nokogiri
    - libxslt-dev # nokogiri
    - mariadb-server
    - memcached
    - openjdk-8-jre-headless
    - redis-server

- name: Install nvm
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm
    update: False
    accept_hostkey: True
