---
- name: install node
  become: True
  tags: [node]
  apt:
    state: present
    pkg:
      - nodejs
      - npm

- name: link node
  file: path=/usr/local/bin/node src=/usr/bin/nodejs state=link
  become: True
  tags: [node]
