---
- hosts: devel
  user: vagrant

  vars:
    gem_bin_path: ~/.rvm/gems/$ruby/bin
    ruby: ruby-2.0.0-p0
    user: vagrant
    wd: /vagrant/src

  tasks:
    - name: set the timezone to MST
      lineinfile: dest=/etc/timezone state=present insertbefore=BOF
                  regexp="^America/Denver" line="America/Denver"
      sudo: True
      notify: [reconfigure tzdata]

    - name: upgrade packages
      apt: upgrade=yes update_cache=yes
      sudo: True

    - name: install userspace packages
      apt: pkg=$item state=installed
      sudo: True
      tags: [packages]
      with_items:
        - ack-grep
        - aspell-en
        - build-essential
        - curl
        - git
        - gnuplot-x11
        - graphviz
        - htop
        - libsqlite3-dev
        - libxml2-dev # Nokogiri
        - libxslt1-dev # Nokogiri
        - libyaml-dev
        - python-software-properties
        - r-base-core
        - screen
        - software-properties-common
        - sqlite3
        - texlive-latex-extra
        - texlive-latex-recommended
        - texlive-xetex
        - tree
        - update-manager-core # for do-release-upgrade -d
        - vim
        - wordnet
        - xorg
        - xstow
        - zsh

    - name: symlink ack-grep to ack
      file: path=/usr/bin/ack src=/usr/bin/ack-grep state=link
      sudo: True
      tags: [packages]

    - name: add the emacs24 PPA
      apt_repository: repo=ppa:cassou/emacs
      sudo: True
      tags: [packages]

    - name: install the latest emacs
      apt: pkg=emacs24-nox state=installed
      sudo: True
      tags: [packages]

    - name: switch to ZSH
      user: name=$user shell=/usr/bin/zsh
      sudo: True
      tags: [packages, users]

    - name: create the src working directory
      file: path=$wd state=directory
      tags: [users]

    - name: clone dotfiles
      git: repo=http://github.com/jmdeldin/dotfiles.git dest=$wd/etc
      tags: [git]

    - name: link dotfiles
      file: path=~/$item src=$wd/etc/$item state=link
      tags: [git]
      with_items:
        - .gitconfig
        - .gitignore
        - .screenrc
        - .vimrc
        - .zshenv
        - .zshrc

    - name: clone .emacs.d
      git: repo=http://github.com/jmdeldin/.emacs.d.git dest=$HOME/.emacs.d
      tags: [git]

    - name: install RVM
      shell: curl -L https://get.rvm.io | bash -s -- --ignore-dotfiles creates=~/.rvm
      tags: [ruby]

    - name: install Ruby 2.0
      shell: rvm install --default $ruby creates=~/.rvm/rubies/$ruby
      tags: [ruby]

    - name: install base gems
      gem: name=$item state=present include_dependencies=False
      tags: [ruby]
      with_items:
        - algoplot
        - nokogiri
        - pry
        - pry-doc
        - rails

  handlers:
    - name: reconfigure tzdata
      shell: dpkg-reconfigure -f noninteractive tzdata
      sudo: True
