---
- hosts: devel
  user: jmdeldin

  vars:
    user: jmdeldin

  tasks:
    - include: system76.yml

    - name: set the timezone to PST
      lineinfile: dest=/etc/timezone state=present insertbefore=BOF
                  regexp="^America/Los_Angeles" line="America/Los_Angeles"
      sudo: True
      notify: [reconfigure tzdata]

    - name: upgrade packages
      apt: upgrade=yes update_cache=yes
      sudo: True

    - apt_repository: repo=ppa:brightbox/ruby-ng
      sudo: True
      tags: [packages]

    # TODO: Future versions of ansible fix the apt_key module to behave
    # like...apt-key
    - name: "add Percona's key"
      shell: apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
      sudo: True
      tags: [mysql]

    - name: add repo for Percona
      apt_repository: repo='{{item}} http://repo.percona.com/apt saucy main'
      sudo: True
      tags: [mysql]
      with_items:
        - deb
        - deb-src

    - name: download elasticsearch
      get_url: dest=~/src/vendor/es.deb url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.10.deb
      tags: [search]

    - name: install elasticsearch
      command: dpkg -i /home/{{user}}/src/vendor/es.deb creates=/etc/init.d/elasticsearch
      sudo: True
      tags: [search]
      notify: [start ES]

    - name: install mysql
      apt: pkg={{item}} state=installed
      sudo: True
      tags: [mysql, packages]
      with_items:
        - percona-server-server-5.6
        - libmysqlclient-dev

    - name: copy my.cnf
      copy: src=templates/etc/mysql/my.cnf dest=/etc/mysql/my.cnf
      sudo: True
      tags: [mysql]

    - name: install userspace packages
      apt: pkg={{item}} state=installed
      sudo: True
      tags: [packages]
      with_items:
        - aspell-en
        - build-essential
        - cloc
        - curl
        - emacs24
        - git
        - gnuplot-x11
        - graphviz
        - htop
        - imagemagick
        - libsqlite3-dev
        - libxml2-dev # Nokogiri
        - libxslt1-dev # Nokogiri
        - libqt4-dev
        - libyaml-dev
        - memcached
        - openjdk-7-jdk
        - python-software-properties
        - pv
        - r-base-core
        - redis-server
        - ruby2.1
        - ruby2.1-dev
        - ruby-switch
        - software-properties-common
        - sqlite3
        - texlive-fonts-recommended
        - texlive-latex-extra
        - texlive-latex-recommended
        - texlive-xetex
        - tmux
        - tree
        - vim
        - wamerican # /usr/share/dict/words
        - whois
        - wordnet
        - zsh

    - name: create the src working directory
      file: path=~/src state=directory
      tags: [users]

    - name: clone dotfiles
      git: repo=http://github.com/jmdeldin/dotfiles.git dest=~/src/etc
      tags: [git]

    - name: link dotfiles
      file: path=~/{{item}} src=~/src/etc/{{item}} state=link
      tags: [git]
      with_items:
        - .gitconfig
        - .gitignore
        - .screenrc
        - .tmux.conf
        - .vimrc
        - .zshenv
        - .zshrc

    - name: switch to ZSH
      user: name={{user}} shell=/usr/bin/zsh
      sudo: True
      tags: [packages, users]

    - name: clone .emacs.d
      git: repo=http://github.com/jmdeldin/.emacs.d.git dest=~/.emacs.d
      tags: [git]

    - name: set ruby version
      command: ruby-switch --set ruby2.1
      sudo: True
      tags: [ruby]

    - name: install base gems
      gem: name={{item}} user_install=yes state=present include_dependencies=True
      tags: [ruby]
      with_items:
        - algoplot
        - bundler
        - db-rotator
        - nokogiri
        - pry
        - pry-doc
        - rails
        - zeus

  handlers:
    - name: reconfigure tzdata
      shell: dpkg-reconfigure -f noninteractive tzdata
      sudo: True

    - name: start ES
      shell: service elasticsearch start
      sudo: True

    - name: restart MySQL
      shell: service mysql restart
      sudo: True
