---
- hosts: devel

  tasks:
    - include: system76.yml

    - name: set the timezone to PST
      lineinfile: dest=/etc/timezone state=present insertbefore=BOF
                  regexp="^America/Los_Angeles" line="America/Los_Angeles"
      sudo: True
      notify: [reconfigure tzdata]

    - name: install aptitude first
      apt: pkg=aptitude state=installed
      sudo: True

    - name: upgrade packages
      apt: upgrade=yes update_cache=yes
      sudo: True
      tags: [maintenance]

    - apt_repository: repo=ppa:hansjorg/rust
      sudo: True
      tags: [packages]

    # TODO: Future versions of ansible fix the apt_key module to behave
    # like...apt-key
    - name: "add Percona's key"
      shell: apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
      sudo: True
      tags: [mysql]

    - name: add repo for Percona
      apt_repository: repo='{{item}} http://repo.percona.com/apt saucy main'
      sudo: True
      tags: [mysql]
      with_items:
        - deb
        - deb-src

    - name: create the src working directory
      file: path=~/src/vendor state=directory
      tags: [users]

    - name: download elasticsearch
      get_url: dest=~/src/vendor/es.deb url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.0.1.deb
      tags: [search]

    - name: install elasticsearch
      command: dpkg -i ~/src/vendor/es.deb creates=/etc/init.d/elasticsearch
      sudo: True
      tags: [search]
      notify: [start ES]

    - name: install mysql
      apt: pkg={{item}} state=installed
      sudo: True
      tags: [mysql, packages]
      with_items:
        - percona-server-server-5.6
        - libmysqlclient-dev

    - name: install userspace packages
      apt: pkg={{item}} state=installed
      sudo: True
      tags: [packages]
      with_items:
        - aspell-en
        - build-essential
        - cloc
        - curl
        - emacs24
        - git
        - gnuplot-x11
        - graphviz
        - htop
        - imagemagick
        - libssl-dev
        - libsqlite3-dev
        - libxml2-dev # Nokogiri
        - libxslt1-dev # Nokogiri
        - libqt4-dev # Capybara
        - libyaml-dev
        - memcached
        - openjdk-7-jdk
        - openssl
        - openssh-server
        - postgresql
        - postgresql-server-dev-9.1
        - python-software-properties
        - pv
        - r-base-core
        - redis-server
        - rust-0.9
        - silversearcher-ag
        - software-properties-common
        - sqlite3
        - texlive-fonts-recommended
        - texlive-latex-extra
        - texlive-latex-recommended
        - texlive-xetex
        - tmux
        - tree
        - vim
        - wamerican # /usr/share/dict/words
        - whois
        - wordnet
        - xsel
        - xvfb # Capybara
        - zsh

    - name: copy my.cnf
      copy: src=templates/etc/mysql/my.cnf dest=/etc/mysql/my.cnf
      sudo: True
      tags: [mysql]
      notify: [restart MySQL]

    - name: clone dotfiles
      git: repo=git@github.com:jmdeldin/dotfiles.git dest=~/src/etc accept_hostkey=yes
      tags: [git]

    - name: link dotfiles
      file: path=~/{{item}} src=~/src/etc/{{item}} state=link
      tags: [git]
      with_items:
        - .gitconfig
        - .gitignore
        - .screenrc
        - .tmux.conf
        - .vimrc
        - .zshenv
        - .zshrc

    - name: switch to ZSH
      user: name={{user}} shell=/usr/bin/zsh
      sudo: True
      tags: [packages, users]

    - name: clone .emacs.d
      git: repo=git@github.com:jmdeldin/.emacs.d.git dest=~/.emacs.d
      tags: [git]

    - name: setup rbenv
      git: repo=git@github.com:sstephenson/rbenv.git dest=~/.rbenv
      tags: [ruby]

    - name: setup ruby-build
      git: repo=git@github.com:sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
      tags: [ruby]

    - name: build ruby version
      command: rbenv install 2.1.1 creates=~/.rbenv/versions/2.1.1
      tags: [ruby]

    - name: set global version
      command: rbenv global 2.1.1
      tags: [ruby]

    - name: install base gems
      gem: name={{item}} state=present include_dependencies=True
      tags: [ruby]
      notify: [rehash ruby gems]
      with_items:
        - algoplot
        - bundler
        - db-rotator
        - hitch
        - mailcatcher
        - nokogiri
        - pry
        - pry-doc
        - rails
        - zeus

    - name: copy iptables
      copy: src=templates/etc/iptables.rules dest=/etc/iptables.rules
      sudo: True
      tags: [net]

    - name: load iptables
      lineinfile: dest=/etc/network/interfaces state=present
                  line="pre-up iptables-restore < /etc/iptables.rules"
      tags: [net]
      sudo: True

  handlers:
    - name: reconfigure tzdata
      shell: dpkg-reconfigure -f noninteractive tzdata
      sudo: True

    - name: start ES
      shell: service elasticsearch start
      sudo: True

    - name: restart MySQL
      shell: service mysql restart
      sudo: True

    - name: rebuild boot image
      command: update-initramfs -u
      sudo: True

    - name: rehash ruby gems
      command: rbenv rehash
