- name: add System76 repo
  sudo: True
  tags: [system76]
  apt_repository: repo='{{item}} http://ppa.launchpad.net/system76-dev/stable/ubuntu {{ubuntu}} main'
  with_items:
    - deb
    - deb-src

- name: install system76 drivers & other GUI software
  apt: pkg={{item}} state=installed
  sudo: True
  tags: [system76, packages]
  with_items:
    - chromium-browser
    - ecryptfs-utils
    - gimp
    - gnome-tweak-tool # set Emacs keybindings + caps lock
    - system76-driver
    - unity-tweak-tool # remove desktop from alt-tab

- name: remove garbage packages
  apt: pkg={{item}} state=absent purge=yes
  sudo: True
  tags: [system76, packages]
  with_items:
    - empathy
    - thunderbird
    - unity-lens-shopping

# SSD optimizations
# https://wiki.debian.org/SSDOptimization
# http://blog.christophersmart.com/2013/06/05/trim-on-lvm-on-luks-on-ssd/
- name: SSD optimization for lvm
  lineinfile: dest=/etc/lvm/lvm.conf state=present backrefs=yes
              regexp="issue_discards = 0" line="issue_discards = 1"
  tags: [ssd]
  sudo: True

- name: SSD optimization for crypttab
  lineinfile: dest=/etc/crypttab state=present backrefs=yes backup=yes
              regexp="(.*) luks" line="\1 luks,discard"
  tags: [ssd]
  sudo: True
  notify: [rebuild boot image]

- cron: name="trim /" hour="9,16" job="fstrim /"
  sudo: True
  tags: [system76]

- cron: name="trim home" hour="9,16" job="fstrim /home"
  sudo: True
  tags: [system76]
