- name: setup System76 drivers
  apt_repository: repo=ppa:system76-dev/stable
  sudo: True
  tags: [system76]

- name: install system76 drivers & other GUI software
  apt: pkg={{item}} state=installed
  sudo: True
  tags: [system76, packages]
  with_items:
    - chromium-browser
    - gcolor2 # color picker
    - gnome-tweak-tool # set Emacs keybindings + caps lock
    - pidgin
    - system76-driver
    - unity-tweak-tool

# SSD optimizations
# https://wiki.debian.org/SSDOptimization
# http://blog.christophersmart.com/2013/06/05/trim-on-lvm-on-luks-on-ssd/
- name: SSD optimization for lvm
  lineinfile: dest=/etc/lvm/lvm.conf state=present backrefs=yes
              regexp="issue_discards = 0" line="issue_discards = 1"
  tags: [ssd]
  sudo: True

- name: SSD optimization for crypttab
  lineinfile: dest=/etc/crypttab state=present backrefs=yes backup=yes
              regexp="(.*) luks" line="\1 luks,discard"
  tags: [ssd]
  sudo: True
  notify: [rebuild boot image]

- cron: name="trim /" hour="9,16" job="fstrim /"
  sudo: True
  tags: [system76]

- cron: name="trim home" hour="9,16" job="fstrim /home"
  sudo: True
  tags: [system76]
