- name: setup System76 drivers
  apt_repository: repo=ppa:system76-dev/stable
  sudo: True
  tags: [system76]

- name: install system76 drivers & other GUI software
  apt: pkg={{item}} state=installed
  sudo: True
  tags: [system76, packages]
  with_items:
    - chromium-browser
    - gnome-tweak-tool # set Emacs keybindings + caps lock
    - system76-driver
    - unity-tweak-tool
