- shell: /bin/true
  register: no_cleanup_by_default

- name: Remove things no one cares about
  when: no_cleanup_by_default is not defined
  tags: janitor
  file: path={{item}} state=absent
  with_items:
    - ~/.android
    - ~/.cache
    - ~/.compiz
    - ~/.gconf
    - ~/.pki
    - ~/.pry_history
    - ~/.sudo_as_admin_successful
    - ~/.xournal
    - ~/.xsel.log
    - ~/.xsession-errors
    - ~/.xsession-errors.old
    - ~/.zcompdump

- shell: /bin/true
  register: no_nuclear_option

- name: Remove the things I do not care about but should ignore (most of the time)
  when: no_nuclear_option is not defined
  tags: nuke
  file: path={{item}} state=absent
  with_items:
    - ~/.Xauthority
    - ~/.bundle
    - ~/.gem
    - ~/.local
    - ~/.mu
    - ~/.npm
    - ~/.rbenv
    - ~/.drum
    - ~/.sorg
