- name: Remove things no one cares about
  when: cleanup is defined
  tags: janitor
  file: path={{item}} state=absent
  with_items:
    - ~/.ICEauthority
    - ~/.android
    - ~/.cache
    - ~/.compiz
    - ~/.gconf
    - ~/.gnome
    - ~/.mozilla
    - ~/.mplayer
    - ~/.pki
    - ~/.pry_history
    - ~/.sudo_as_admin_successful
    - ~/.thumbnails
    - ~/.xournal
    - ~/.xsel.log
    - ~/.xsession-errors
    - ~/.xsession-errors.old
    - ~/.zcompdump

- name: Remove semi-useful but mostly garbage directories
  when: nuclear is defined
  tags: janitor
  file: path={{item}} state=absent
  with_items:
    - ~/.Xauthority
    - ~/.bundle
    - ~/.gem
    - ~/.local
    - ~/.mu
    - ~/.npm
    - ~/.rbenv
