- name: remove garbage packages
  apt: name={{item}} state=absent purge=yes
  become: True
  tags: janitor, packages
  with_items:
    - at-spi2-core
    - brltty # not sure how these packages end up on ubuntu 17.10
    - cheese
    - deja-dup
    - empathy
    - exim4
    - exim4-base
    - exim4-config
    - gconf2
    - geoclue-2.0
    - gnome-keyring
    - gnome-mahjongg
    - gnome-mines
    - libgeoclue-2.0
    - libgnome-keyring-common
    - lxc
    - lxc-common
    - lxcfs
    - lxd
    - lxd-client
    - open-iscsi
    - open-vm-tools
    - pastebinit
    - pinentry-gnome3
    - rhythmbox
    - shotwell
    - snapd
    - thunderbird
    - totem
    - ubuntu-advantage-tools
    - unity-lens-shopping
    - unity-webapps
    - xbrlapi

- name: Remove things no one cares about
  when: cleanup is defined
  tags: janitor
  file: path={{item}} state=absent
  with_items:
    - ~/.ICEauthority
    - ~/.android
    - ~/.cache/0ad
    - ~/.cache/chromium
    - ~/.cache/darktable
    - ~/.compiz
    - ~/.lesshst
    - ~/.gconf
    - ~/.gnome
    - ~/.mplayer
    - ~/.pki
    - ~/.profile
    - ~/.pry_history
    - ~/.selected_editor
    - ~/.sudo_as_admin_successful
    - ~/.thumbnails
    - ~/.viminfo
    - ~/.wicd
    - ~/.xournal
    - ~/.xsel.log
    - ~/.xsession-errors
    - ~/.xsession-errors.old
    - ~/.zcompdump

- name: Remove semi-useful but mostly garbage directories
  when: nuclear is defined
  tags: janitor
  file: path={{item}} state=absent
  with_items:
    - ~/.Xauthority
    - ~/.bundle
    - ~/.gem
    - ~/.local
    - ~/.mu
    - ~/.npm
    - ~/.rbenv
