- name: remove garbage packages
  apt: name={{item}} state=absent purge=yes
  become: True
  tags: janitor, packages
  with_items:
    - at-spi2-core
    - brltty # not sure how these packages end up on ubuntu 17.10
    - cheese
    - deja-dup
    - empathy
    - exim4
    - exim4-base
    - exim4-config
    - gnome-keyring
    - gnome-mahjongg
    - gnome-mines
    - lxc
    - lxd
    - pinentry-gnome3
    - rhythmbox
    - shotwell
    - snapd
    - thunderbird
    - totem
    - unity-lens-shopping
    - unity-webapps
    - xbrlapi

- name: Remove things no one cares about
  when: cleanup is defined
  tags: janitor
  file: path={{item}} state=absent
  with_items:
    - ~/.ICEauthority
    - ~/.android
    - ~/.cache
    - ~/.compiz
    - ~/.lesshst
    - ~/.gconf
    - ~/.gnome
    - ~/.mozilla
    - ~/.mplayer
    - ~/.pki
    - ~/.pry_history
    - ~/.sudo_as_admin_successful
    - ~/.thumbnails
    - ~/.xournal
    - ~/.xsel.log
    - ~/.xsession-errors
    - ~/.xsession-errors.old
    - ~/.zcompdump

- name: Remove semi-useful but mostly garbage directories
  when: nuclear is defined
  tags: janitor
  file: path={{item}} state=absent
  with_items:
    - ~/.Xauthority
    - ~/.bundle
    - ~/.gem
    - ~/.local
    - ~/.mu
    - ~/.npm
    - ~/.rbenv
