---
- name: remove garbage packages
  apt: name={{item}} state=absent purge=yes
  become: True
  tags: [packages]
  with_items:
    - cheese
    - deja-dup
    - empathy
    - exim4
    - exim4-base
    - exim4-config
    - gnome-mahjongg
    - gnome-mines
    - rhythmbox
    - shotwell
    - thunderbird
    - totem
    - unity-lens-shopping
    - unity-webapps

- name: install basic system packages
  become: True
  apt: name={{item}} state=installed
  with_items:
    - git
    - htop
    - rsync
