---
- name: Install deps for gems
  apt: pkg={{item}} state=present
  become: True
  tags: [ruby]
  with_items:
    - autoconf # rbenv
    - bison # rbenv
    - build-essential
    - libffi-dev # rbenv
    - libgdbm-dev # rbenv
    - libncurses-dev # rbenv
    - libreadline-dev # rbenv
    - libsqlite3-dev
    - libyaml-dev # rbenv
    - sqlite3
    - zlib1g-dev # rbenv

- name: Install deps for >= 2.3 ruby
  apt: pkg={{item}} state=present
  become: True
  tags: [ruby]
  with_items:
    - libssl-dev # rbenv
    - libcurl4-openssl-dev
  when: old_ruby is not defined

- name: Install deps for < 2.3 ruby
  apt: pkg={{item}} state=present
  become: True
  tags: [ruby]
  with_items:
    - libcurl3
    - libcurl-openssl1.0-dev
    - libssl1.0-dev
  when: old_ruby is defined

- name: setup rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv
    update: False
    accept_hostkey: True
  tags: [ruby]

- name: setup ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    update: False
  tags: [ruby]

- name: install default ruby
  shell: ~/.rbenv/bin/rbenv install {{default_ruby}}
  args:
    creates: ~/.rbenv/versions/{{default_ruby}}
  when: default_ruby is defined

- name: set default ruby
  shell: ~/.rbenv/bin/rbenv global {{default_ruby}}
  args:
    creates: ~/.rbenv/version
  when: default_ruby is defined

- name: install bundler
  shell: ~/.rbenv/shims/gem install bundler --version {{bundler_version}}
  args:
    creates: ~/.rbenv/shims/bundler
  when: bundler_version is defined
