---
- name: Install deps for gems
  apt: pkg={{item}} state=installed
  become: True
  tags: [ruby]
  with_items:
    - build-essential
    - libffi-dev # rbenv
    - libreadline-dev # rbenv
    - libsqlite3-dev # sqlite
    - libssl-dev # rbenv
    - libyaml-dev # rbenv
    - sqlite3

- name: setup rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv
    update: False
    accept_hostkey: True
  tags: [ruby]

- name: setup ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    update: False
  tags: [ruby]
